name: Windows

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:
  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: configure
      run: |
        cd Build 
        cmake -G "Visual Studio 17 2022" -A x64 ..
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: build
      run: |
        msbuild Build/ALL_BUILD.vcxproj -p:Configuration=Release -p:Platform=x64 -m
#   - name: test
#     run: cd build && ctest
    - name: deploy_dev
      if: github.ref == 'refs/heads/development-juce8'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      run: |
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DLLs/FrontPanelUSB-DriverOnly-4.5.5.exe open-ephys
        cp -r ../Resources/DLLs/FTD3XXDriver_WHQLCertified_1.3.0.8_Installer.exe open-ephys
        cp ../LICENSE open-ephys
        cp C:/Windows/System32/msvcp140.dll open-ephys
        cp C:/Windows/System32/vcruntime140.dll open-ephys
        cp C:/Windows/System32/vcruntime140_1.dll open-ephys
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        zipfile=open-ephys-v1.0.0-dev-windows.zip
        powershell Compress-Archive -Path "open-ephys" -DestinationPath ${zipfile}
        user_info="X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN"
        curl -H $user_info -T $zipfile "https://openephys.jfrog.io/artifactory/GUI-binaries/1.0.0-dev/windows/$zipfile"
      shell: bash
    - name: deploy_preview
      if: github.ref == 'refs/heads/testing-juce8'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      run: |
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DLLs/FrontPanelUSB-DriverOnly-4.5.5.exe open-ephys
        cp -r ../Resources/DLLs/FTD3XXDriver_WHQLCertified_1.3.0.8_Installer.exe open-ephys
        cp ../LICENSE open-ephys
        cp C:/Windows/System32/msvcp140.dll open-ephys
        cp C:/Windows/System32/vcruntime140.dll open-ephys
        cp C:/Windows/System32/vcruntime140_1.dll open-ephys
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        zipfile=open-ephys-v1.0.0-alpha.1-windows.zip
        powershell Compress-Archive -Path "open-ephys" -DestinationPath ${zipfile}
        user_info="X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN"
        curl -H $user_info -T $zipfile "https://openephys.jfrog.io/artifactory/GUI-binaries/1.0.0-alpha/windows/$zipfile"

        cd open-ephys
        rm -f msvcp140.dll vcruntime140.dll vcruntime140_1.dll
        cd ../../Resources/Installers/Windows
        iscc "windows_installer_script.iss"
        installer=Install-Open-Ephys-GUI-v1.0.0-alpha.1.exe
        mv Open-Ephys_Installer.exe $installer
        curl -H $user_info -T $installer "https://openephys.jfrog.io/artifactory/GUI-binaries/1.0.0-alpha/windows/$installer"
      shell: bash
